apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kerry.service: pvc-upload-image
  name: pvc-upload-image
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kerry.service: pvc-mariadb
  name: pvc-mariadb
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
